# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-09 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.CharField(max_length=5)),
                ('goodsimg', models.CharField(max_length=100)),
                ('goodsname', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('descript', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgpath', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'nav',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgpath', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'wheel',
            },
        ),
    ]
