# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WYKL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgpath', models.CharField(max_length=30)),
            ],
        ),
    ]
