# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WYKL', '0002_wheel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wheel',
            table='wheel',
        ),
    ]
